# Copyright (C) 2019  Christian Berger
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

version: '2.3'
services:
    frame-feed-evaluator:
        container_name: ffe
        build:
            context: https://github.com/chrberger/frame-feed-evaluator.git#v0.0.3
            dockerfile: Dockerfile.amd64
        network_mode: "host"
        ipc: "host"
        volumes:
        - /tmp:/tmp
        - $PWD:/host
        - $PWD/example:/pngs
        working_dir: /host
        environment:
        - DISPLAY=$DISPLAY
        command: "--folder=/pngs --report=ffe-qsv.csv --cid=111 --name=video0 --crop.x=376 --crop.y=32 --crop.width=640 --crop.height=480 --delay=0"

    video-qsv-encoder-amd64:
        container_name: qsv-h264
        depends_on:
        - frame-feed-evaluator
        devices:
        - /dev/dri/renderD128
        image: chrberger/video-qsv-h264-encoder:v0.0.4
        network_mode: "host"
        ipc: "host"
        volumes:
        - /tmp:/tmp
        command: "--cid=111 --name=video0 --width=640 --height=480 --bitrate=3000"
